### ISSUE TITLE
variantFilter causing an issue.

### ISSUE THREAD

**Issue by MungoRae** [googlecodelabs/android-testing#14] opened 2016-01-20 11:31 UTC
Cloning this and opening in Android Studio 1.5.1 I get the following error:

    Error:(35, 0) No signature of method: java.lang.String.variantFilter() is applicable for argument types: (build_8svktq4s2wa741jcavj9ayd99$_run_closure1_closure8) values: [build_8svktq4s2wa741jcavj9ayd99$_run_closure1_closure8@191ee85a]

This refers to the `app/build.gradle` line

    // Remove mockRelease as it's not needed.
    android.variantFilter { variant ->
        if(variant.buildType.name.equals('release')
                && variant.getFlavors().get(0).name.equals('mock')) {
            variant.setIgnore(true);
        }
    }

I tried changing `android.variantFilter` to `applicationVariants.all` which then moved the problem to `getFlavors()`.

Am I using the wrong version of gradle?

**Comment by slinzner** [comment] 2016-05-11 19:28
Is this still an issue with 2.0/2.1, I actually cannot reproduce it.

**Comment by slinzner** [comment] 2016-05-13 15:21
Closing this issue for now, please re-open if you think this is still an issue.

**Closed by slinzner** 2016-05-13 15:21 UTC
Labels: question
