### ISSUE TITLE
Step 5 references the NotesPresenter object in a different method.

### ISSUE THREAD

**Issue by anyercastillo** [googlecodelabs/android-testing#47] opened 2016-05-19 06:01 UTC
https://codelabs.developers.google.com/codelabs/android-testing/index.html?index=..%2F..%2Findex#4

In the section `Creating the NotesPresenter`
The NotesPresenter object  is created in `onCreate(...)` instead of `onActivityCreated(...)`

Thank you.

**Comment by jfschmakeit** [comment] 2017-01-10 04:04
Dupe of issue #68 . Fixed in the next doc release.

**Closed by jfschmakeit** 2017-01-10 04:04 UTC
Labels: enhancement
